### ISSUE TITLE
e

### ISSUE THREAD

**Issue by Snivyer1910** [ChillTeensie/sarvente-kade#1]
e

**Comment by Rajbir98** [comment]
a

**Comment by AbnormalPoof** [comment]
sports

**Comment by Rajbir98** [comment]
Hey, I have Made A new version of this mod in kade engine 1.5 I used Garcello kade engine as the base and an animation mod to add better boyfriend and girlfriend animation I haven't coded any thin cause I don't know how to but I have replaced files and made it work and it's better than your one but the problem is I can't get rid of the names just like the mod is stilled named with garcello will you help me I have completed its work till ruvs song. If You Want I can send u gameplay, and one more I have used agoti arrows

**Comment by ChillTeensie** [comment]
> Hey, I have Made A new version of this mod in kade engine 1.5 I used Garcello kade engine as the base and an animation mod to add better boyfriend and girlfriend animation I haven't coded any thin cause I don't know how to but I have replaced files and made it work and it's better than your one but the problem is I can't get rid of the names just like the mod is stilled named with garcello will you help me I have completed its work till ruvs song. If You Want I can send u gameplay, and one more I have used agoti arrows

https://gamebanana.com/tuts/13798

**Comment by Rajbir98** [comment]
> > Hey, I have Made A new version of this mod in kade engine 1.5 I used Garcello kade engine as the base and an animation mod to add better boyfriend and girlfriend animation I haven't coded any thin cause I don't know how to but I have replaced files and made it work and it's better than your one but the problem is I can't get rid of the names just like the mod is stilled named with garcello will you help me I have completed its work till ruvs song. If You Want I can send u gameplay, and one more I have used agoti arrows
> 
> https://gamebanana.com/tuts/13798

Not enough internet to download files and not enough storage i am just a 14 yrs old boy and i dont have a good pc so i want u use the assets in my mod to make it better i will send u the gameplay as i complete gospel

**Comment by Rajbir98** [comment]
after all i can get storage but not internet

**Comment by Rajbir98** [comment]
ok
